ietf-wg-dult/threat-model

draft-delano-dult-threat-model.md

Draft of abstract

---

draft-delano-dult-threat-model.md

Filled in drafted content for an introduction section and a security/taxonomy section. Second commit was fixing minor formatting errors from my first commit.

Introduction and Security/Taxonomy section

---

draft-delano-dult-threat-model.md

Updated levels of access to technological safeguards

Updated levels of access to technological safeguards

---

draft-ietf-dult-threat-model.md

Remove tabs

---

README.md

Fkx Editor's Copy link

---

draft-ietf-dult-threat-model.md

Adds expectation of unwanted location tracking (#21, parent issue #19). @exploretechsafety should add information for addressing #20 before merging.

Add expectation of unwanted tracking to victim taxonomy

---

draft-ietf-dult-threat-model.md

Just integrate the text from the two authors better and also add that platforms should include instructions on how to disable trackers.

refer to tracking tag alerts section and add instructions for platforms

---

draft-ietf-dult-threat-model.md

This PR adds text related to Confidence-based Threat Alerts to users in Section 4.1.1.2

Adding Confidence-based Threat Alerts to draft-ietf-dult-threat-model

---

draft-ietf-dult-threat-model.md

This PR adds:
1. Additional threats to Section 3.2
2. Introducing a Threat Matrix in Section 3.3

Adding Threat Matrix and additional Threats to Section 3.3 and Section 3.2 respectively of draft-ietf-dult-threat-model

---

draft-ietf-dult-threat-model.md

This PR adds text to Device Constraints in Section 4.2.3, and hence resolves https://github.com/ietf-wg-dult/threat-model/issues/52

Adding Description to Device Constraints Section 4.2.3

---

draft-ietf-dult-threat-model.md

This PR adds text to **Power Constraints** in **Section 4.2.2**, and hence resolves https://github.com/ietf-wg-dult/threat-model/issues/51

Elaborate on Power Constraints in Section 4.2.2

---

draft-ietf-dult-threat-model.md

Just add minor clarifications: which attacks are in scope, finding options, BLE constraints.

Minor updates to attacks and finding

---

draft-ietf-dult-threat-model.md

This PR adds BLR Protocol Constraints to Section 4.2.1 of the DULT Threat Model draft, and hence addresses https://github.com/ietf-wg-dult/threat-model/issues/57 and https://github.com/ietf-wg-dult/threat-model/issues/23

Adding BLE Protocol Constraints to Design Constraints

---

draft-ietf-dult-threat-model.md

Resolves https://github.com/ietf-wg-dult/threat-model/issues/82

Adding text for the case where disabling owner's device bluetooth results in false positives

---

draft-ietf-dult-threat-model.md

Resolves https://github.com/ietf-wg-dult/threat-model/issues/83

Changing non-compliant to non-conformant to align with other DULT drafts

---

draft-ietf-dult-threat-model.md

Resolves https://github.com/ietf-wg-dult/threat-model/issues/86

Adding text for Notification Management for Trusted Devices

---

draft-ietf-dult-threat-model.md

Resolves https://github.com/ietf-wg-dult/threat-model/issues/80

Adding text for Advices when unwanted trackers are found

---

draft-ietf-dult-threat-model.md

But that it is optional; resolves #78.

Specify that laptops may implement protocol

---

.idea/misc.xml
.idea/modules.xml
.idea/threat-model.iml
.idea/vcs.xml
.idea/workspace.xml
draft-ietf-dult-threat-model.md

Adding suggestions for resolving #67

Resolving #67

---

draft-ietf-dult-threat-model.md

fix threat matrix table titles to match section titles

---

draft-ietf-dult-threat-model.md

New PR because of permissions issues with old one. Closes #113, closes #133.

Delano gps tracker

---

draft-ietf-dult-threat-model.md

Expands scenarios to incorporate expanded taxonomy, adds acquaintance scenario. Addresses #61

Expands scenarios to incorporate expanded taxonomy
